# .gitpod.yml

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - eventyret.bootstrap-4-cdn-snippet
    - formulahendry.auto-close-tag
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-python.debugpy
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow

tasks:
  - init: npm install
  - command: npm run dev
